name: CI

on:
  push:
    branches:
      - "main"


jobs:
  deploy:
    name: "Sync repos"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/*
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking yes
          END
        env:
          SSH_USER: ${{ secrets.DEPLOY_SSH_USER }}
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
          SSH_HOST_KEY: ${{ secrets.DEPLOY_SSH_HOST_KEY }}

      - name: Login to Container registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - uses: actions/checkout@v3.1.0
      - name: Build frontend image
        run: |
          docker build frontend --file Dockerfile --tag ghcr.io/mirorauhala/trade-front:latest
          docker push ghcr.io/mirorauhala/trade-front:latest

      - uses: actions/checkout@v3.1.0
      - name: Build backend image
        run: |
          docker build strapi --file Dockerfile --tag ghcr.io/mirorauhala/trade-back:latest
          docker push ghcr.io/mirorauhala/trade-back:latest

      - name: Login to Container registry on prod
        run: ssh prod 'echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u "${{ github.actor }}" --password-stdin'

      - name: Start app
        run: ssh prod 'cd app && touch githubwashere'

      - name: Checkout
        uses: actions/checkout@v3.1.0
      - run: |
          rm -rf .git

      - name: "Commit: frontend"
        uses: actions/checkout@v3
        with:
          repository: mirorauhala/trade-front
          path: deploy-frontend
          token: ${{ secrets.GH_PAT }}
      - run: |
          rsync -av --delete --exclude=.git frontend/ deploy-frontend/
          cd deploy-frontend
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Sync: $(date +"%Y-%m-%dT%H:%M:%S")"
          git push

      - name: "Commit: backend"
        uses: actions/checkout@v3
        with:
          repository: mirorauhala/trade-back
          path: deploy-backend
          token: ${{ secrets.GH_PAT }}
      - run: |
          rsync -av --delete --exclude=.git strapi/ deploy-backend/
          cd deploy-backend
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Sync: $(date +"%Y-%m-%dT%H:%M:%S")"
          git push
